# Generated by Django 5.0.7 on 2024-07-24 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место выполнения привычки')),
                ('start_time', models.TimeField(verbose_name='Время выполнения привычки')),
                ('action', models.CharField(max_length=200, verbose_name='Дествие привычки')),
                ('is_pleasant', models.BooleanField(default=True, verbose_name='Признак приятной привычки')),
                ('periodicity', models.IntegerField(default=1, verbose_name='Периодичность выполнения привычки')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('execution_time', models.DurationField(blank=True, default=datetime.timedelta(seconds=60), null=True, verbose_name='Время на выполнение привычки')),
                ('is_published', models.BooleanField(default=True, verbose_name='Признак публичности')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
